services:
  backend:
    build: 
      context: ./Recycleware-Backend
    container_name: recycleware-backend
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app/data
    restart: always

  frontend:
    build: 
      context: ./RecycleWare---ReactFronted
    container_name: recycleware-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
