-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 12:49:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recycleware
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recycleware
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recycleware` DEFAULT CHARACTER SET utf8 ;
USE `recycleware` ;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(6) NOT NULL,
  `razon_social` VARCHAR(45) NULL DEFAULT 'null',
  `nombre_contacto` VARCHAR(45) NULL DEFAULT 'null',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorias_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias_producto` ;

CREATE TABLE IF NOT EXISTS `categorias_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estados_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estados_producto` ;

CREATE TABLE IF NOT EXISTS `estados_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

CREATE TABLE IF NOT EXISTS `productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `id_idx1` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categorias_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estados_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `donaciones` ;

CREATE TABLE IF NOT EXISTS `donaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_donante` INT NULL DEFAULT NULL,
  `fecha_donacion` DATE NOT NULL,
  `donacionescol` VARCHAR(45) NOT NULL,
  `cantidad_productos` INT NOT NULL DEFAULT 1,
  `descripcion` VARCHAR(200) NOT NULL,
  `peso` FLOAT NULL,
  `volumen` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_donante` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id_donante`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estados_solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estados_solicitud` ;

CREATE TABLE IF NOT EXISTS `estados_solicitud` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `solicitudes` ;

CREATE TABLE IF NOT EXISTS `solicitudes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_solicitante` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `id_estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_solicitante` ASC) VISIBLE,
  INDEX `id_idx1` (`id_producto` ASC) VISIBLE,
  INDEX `id_idx2` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id_solicitante`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id_producto`)
    REFERENCES `productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estados_solicitud` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensajes_contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mensajes_contacto` ;

CREATE TABLE IF NOT EXISTS `mensajes_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `asunto` VARCHAR(45) NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `categorias_producto`
-- -----------------------------------------------------
START TRANSACTION;
USE `recycleware`;
INSERT INTO `categorias_producto` (`id`, `nombre`) VALUES (0, 'Periféricos');
INSERT INTO `categorias_producto` (`id`, `nombre`) VALUES (1, 'Portatiles');
INSERT INTO `categorias_producto` (`id`, `nombre`) VALUES (2, 'Sobremesa');
INSERT INTO `categorias_producto` (`id`, `nombre`) VALUES (3, 'Componentes');

COMMIT;


-- -----------------------------------------------------
-- Data for table `estados_producto`
-- -----------------------------------------------------
START TRANSACTION;
USE `recycleware`;
INSERT INTO `estados_producto` (`id`, `nombre`) VALUES (0, 'Bueno');
INSERT INTO `estados_producto` (`id`, `nombre`) VALUES (1, 'Funcional');
INSERT INTO `estados_producto` (`id`, `nombre`) VALUES (2, 'Roto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `estados_solicitud`
-- -----------------------------------------------------
START TRANSACTION;
USE `recycleware`;
INSERT INTO `estados_solicitud` (`id`, `nombre`) VALUES (0, 'Pendiente');
INSERT INTO `estados_solicitud` (`id`, `nombre`) VALUES (1, 'Denegada');
INSERT INTO `estados_solicitud` (`id`, `nombre`) VALUES (2, 'Aprobada');
INSERT INTO `estados_solicitud` (`id`, `nombre`) VALUES (3, 'Entregada');

COMMIT;

