# Nombre de la aplicacion
spring.application.name=Recycleware

# URL base para tu API (ej: http://localhost:8080/api)
server.servlet.context-path=/api

# Configuracion H2 Database (Modo fichero)
# Guardara la BD en una carpeta 'data' en la raiz de tu proyecto backend
spring.datasource.url=jdbc:h2:file:./data/recyclewareDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 habilitada en http://localhost:8080/api/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# JPA y SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# IMPORTANTE: Como usas 'validate', Spring NO creara las tablas automaticamente.
spring.jpa.hibernate.ddl-auto=validate

# Para mostrar las consultas en la consola
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false

# Inicializacion de datos (Ejecutara schema.sql al inicio)
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true